exp_root_dir : "/data/mml/backdoor_detect/experiments"
# CIFAR-10 dataset dir
CIFAR10_dataset_dir: /data/mml/backdoor_detect/dataset/cifar10
# GTSRB dataset dir
GTSRB_dataset_dir: /data/mml/backdoor_detect/dataset/GTSRB
# ImageNet2012_subset dir
ImageNet2012_subset_dir: /data/mml/backdoor_detect/dataset/ImageNet2012_subset

global_random_seed: 0
# attacked class
target_class: 3
poisoned_rate: 0.05

dataset_name_list: CIFAR10, GTSRB, ImageNet2012_subset
model_name_list: ResNet18, VGG19, DenseNet
attack_name_list: BadNets, IAD, Refool, WaNet