CIFAR10:
    ResNet18:
        BadNets:
            exp_1: "2025-06-05_12:13:46" # random_seed: 1
            exp_2: "2025-06-09_16:04:11" 
            exp_3: "2025-06-10_19:49:02"
            exp_4: "2025-06-08_21:52:02"
            exp_5: "2025-06-10_19:52:30"
            exp_6:
            exp_7: "2025-06-08_21:52:25"
            exp_8:
            exp_9:
            exp_10: "2025-06-08_21:53:12"
        IAD:
            exp_1: "2025-06-05_18:21:24"
            exp_2:
            exp_3:
            exp_4: "2025-06-09_02:46:56"
            exp_5:
            exp_6:
            exp_7: "2025-06-09_04:10:33"
            exp_8:
            exp_9:
            exp_10: "2025-06-09_04:17:36"
        Refool:
            exp_1: "2025-06-06_06:32:25"
            exp_2:
            exp_3:
            exp_4: "2025-06-09_08:05:40"
            exp_5:
            exp_6:
            exp_7: "2025-06-09_09:51:42"
            exp_8:
            exp_9:
            exp_10: "2025-06-09_09:53:14"
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4: "2025-06-09_15:06:46"
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
    VGG19:
        BadNets:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9: 
            exp_10:
        IAD:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8: 
            exp_9:
            exp_10:
        Refool:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
    DenseNet:
        BadNets:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        IAD:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        Refool:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
GTSRB:
    ResNet18:
        BadNets:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        IAD:
            exp_1:
            exp_2: "2025-06-17_01:42:09"
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        Refool:
            exp_1: "2025-06-17_04:22:15"
            exp_2: "2025-06-17_05:11:11"
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        WaNet:
            exp_1:
            exp_2: "2025-06-17_09:03:28"
            exp_3: "2025-06-15_22:13:09"
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
    VGG19:
        BadNets:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        IAD:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        Refool:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
    DenseNet:
        BadNets:
            exp_1: 
            exp_2:
            exp_3:
            exp_4: "2025-06-17_12:32:26"
            exp_5: "2025-06-17_12:32:40"
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        IAD:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        Refool:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:  
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
ImageNet2012_subset:
    ResNet18:
        BadNets:
            exp_1: "2025-06-13_23:24:58"
            exp_2: "2025-06-14_15:40:20"
            exp_3: "2025-06-14_15:41:28"
            exp_4: "2025-06-14_15:41:35"
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        IAD:
            exp_1: "2025-06-14_05:46:34"
            exp_2: "2025-06-15_20:30:58"
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        Refool:
            exp_1:
            exp_2: "2025-06-16_15:46:49"
            exp_3: "2025-06-16_17:32:41"
            exp_4: "2025-06-15_17:16:21"
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4: "2025-06-16_03:01:25"
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
    DenseNet:
        BadNets:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: "2025-06-05_20:51:56"
        IAD:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        Refool:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 