CIFAR10:
    ResNet18:
        BadNets:
            exp_1: 
            exp_2:  
            exp_3: 
            exp_4: 
            exp_5: 
            exp_6:
            exp_7: 
            exp_8:
            exp_9:
            exp_10: 
        IAD:
            exp_1: 
            exp_2:
            exp_3:
            exp_4: 
            exp_5:
            exp_6:
            exp_7: 
            exp_8:
            exp_9:
            exp_10: 
        Refool:
            exp_1: 
            exp_2:
            exp_3:
            exp_4: 
            exp_5:
            exp_6:
            exp_7: 
            exp_8:
            exp_9:
            exp_10: 
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4: 
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
    VGG19:
        BadNets:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9: 
            exp_10:
        IAD:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8: 
            exp_9:
            exp_10:
        Refool:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
    DenseNet:
        BadNets:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        IAD:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        Refool:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
GTSRB:
    ResNet18:
        BadNets:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        IAD:
            exp_1:
            exp_2: 
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        Refool:
            exp_1: 
            exp_2: 
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        WaNet:
            exp_1:
            exp_2: 
            exp_3: 
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
    VGG19:
        BadNets:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        IAD:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        Refool:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
    DenseNet:
        BadNets:
            exp_1: 
            exp_2:
            exp_3:
            exp_4: 
            exp_5: 
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        IAD:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        Refool:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:  
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
ImageNet2012_subset:
    ResNet18:
        BadNets:
            exp_1: 
            exp_2: 
            exp_3: 
            exp_4: 
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        IAD:
            exp_1: 
            exp_2: 
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        Refool:
            exp_1:
            exp_2: 
            exp_3: 
            exp_4: 
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4: 
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
    DenseNet:
        BadNets:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        IAD:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10:
        Refool:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 
        WaNet:
            exp_1:
            exp_2:
            exp_3:
            exp_4:
            exp_5:
            exp_6:
            exp_7:
            exp_8:
            exp_9:
            exp_10: 